import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import { useForm } from "react-hook-form";

export default function Home() {
    const { handleSubmit } = useForm();

    function onSubmit(data) {
        console.log("DATA:", data);
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="p-10" id="__layout">
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Scattergories!</a>
                </h1>

                <div className="h-100">
                    <form
                        onSubmit={handleSubmit(onSubmit)}
                        className="d-flex flex-column align-items-center justify-content-center h-100 w-100"
                    >
                        <div className="w-100 p-40">
                            <label className="font-size-h6 font-weight-bolder">Display Name</label>
                            <input
                                type="name"
                                className="form-control form-control-solid h-auto rounded-lg font-size-h6 py-7 px-6"
                                placeholder="Enter your name"
                            />
                        </div>

                        <button type="submit" className="btn btn-success btn-lg">
                            Join Lobby
                        </button>
                    </form>
                </div>
            </main>
        </>
    );
}
