import Head from "next/head";
import styles from "../styles/Home.module.css";
import firebase from "firebase";
import classNames from "classnames";
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";
import React from "react";

export default function Home() {
    const { handleSubmit, register, formState } = useForm({ mode: "onChange" });
    const router = useRouter();

    async function onSubmit(data) {
        await firebase.firestore().doc(`/users/${data.name}`).set(
            {
                name: data.name,
                answers: [],
            },
            { merge: true }
        );

        router.push("/lobby");
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="p-10" id="__layout">
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Scattergories!</a>
                </h1>

                <form
                    onSubmit={handleSubmit(onSubmit)}
                    className="d-flex flex-column align-items-center justify-content-center h-100 w-100"
                >
                    <div className="w-100 p-40">
                        <label className="font-size-h6 font-weight-bolder">Display Name</label>
                        <input
                            ref={register({
                                required: true,
                                pattern: {
                                    value: ".+",
                                    message: "Must add a name",
                                },
                            })}
                            name="name"
                            type="name"
                            className="form-control form-control-solid h-auto rounded-lg font-size-h6 py-7 px-6"
                            placeholder="Enter your name"
                        />
                    </div>

                    <button
                        type="submit"
                        className={classNames("btn btn-success btn-lg ", {
                            "spinner spinner-left": formState.isSubmitting,
                        })}
                        disabled={!formState.isValid}
                    >
                        Join Lobby
                    </button>
                </form>

                <button
                    className="btn btn-success btn-lg w-50 align-self-center mb-30"
                    onClick={() => onStartGameClick()}
                >
                    Start Game
                </button>
            </main>
        </>
    );
}
